"""Brute-force census of the 2-subgroups of S_n for n <= 8, on explicit permutations.

Every 2-subgroup of S_8 lies in a Sylow 2-subgroup, and those are all conjugate.
So this script

  1. builds one Sylow 2-subgroup S = C2 wr C2 wr C2 of S_8 (order 128);
  2. lists every subgroup of S by repeated descent to maximal subgroups.  In a
     2-group every subgroup is reached that way, and the maximal subgroups of a
     2-group M are the preimages of the hyperplanes of M/Phi(M), where the
     Frattini subgroup Phi(M) is generated by the squares;
  3. conjugates that list by a left transversal of S in S_8 (8!/128 = 315
     elements; S is self-normalising, so these are the 315 Sylow subgroups)
     and deduplicates, which gives every 2-subgroup of S_8;
  4. checks, for every n <= 8, the per-order totals and the number of
     S_n-conjugacy classes per order against data/lattice_n{n}.json, written
     by the independent C enumerator src/subgroups.c, checks the
     elementary abelian totals against elemab.py and NOTES.md, and checks the
     transitive classes of degree 8 against the TransitiveGroups library.

From that list it records

  * the transitive 2-subgroups P of S_b for b = 1, 2, 4, 8, with the rank
    d(P) = dim P/Phi(P), |Phi(P)|, and their S_b-conjugacy classes;
  * for each n <= 8, the number of Frattini-closed 2-subgroups H <= S_n and
    their order histogram.  H is Frattini-closed if, for every orbit O,
    H contains Phi(H|O), where H|O is H restricted to O and extended by the
    identity off O.

Nothing here knows the counting formula of src/block_families.py.  That script
reads the census and has to reproduce the Frattini-closed totals from it.

Exit status 0 only if every cross-check passes.
"""

from __future__ import annotations

import argparse
import itertools
import json
import pathlib
import sys
import time
from collections import Counter

ROOT = pathlib.Path(__file__).resolve().parent.parent
DEG = 8
ID = tuple(range(DEG))

# Elementary abelian 2-subgroups of S_8 by rank, NOTES.md section 2.2
# (rank_counts(8)); e(n) for n <= 7 is recomputed from elemab.py below.
EXPECTED_RANKS_N8 = [1, 763, 6685, 4440, 350]


def compose(p: tuple, q: tuple) -> tuple:
    """(p*q)(i) = p(q(i)): q acts first."""
    return tuple(p[i] for i in q)


def inverse(p: tuple) -> tuple:
    inv = [0] * len(p)
    for i, x in enumerate(p):
        inv[x] = i
    return tuple(inv)


def encode(p: tuple) -> int:
    c = 0
    for i, x in enumerate(p):
        c |= x << (3 * i)
    return c


def decode(c: int) -> tuple:
    return tuple((c >> (3 * i)) & 7 for i in range(DEG))


def from_cycles(cycles: list[tuple]) -> tuple:
    p = list(range(DEG))
    for cyc in cycles:
        for a, b in zip(cyc, cyc[1:] + cyc[:1]):
            p[a] = b
    return tuple(p)


ID_CODE = encode(ID)


def bits(mask: int) -> list[int]:
    out = []
    while mask:
        low = mask & -mask
        out.append(low.bit_length() - 1)
        mask ^= low
    return out


# ------------------------------------------------------------ the Sylow group


def build_sylow():
    gens = [
        from_cycles([(0, 1)]),
        from_cycles([(0, 2), (1, 3)]),
        from_cycles([(0, 4), (1, 5), (2, 6), (3, 7)]),
    ]
    elems = [ID]
    index = {ID: 0}
    frontier = [ID]
    while frontier:
        nxt = []
        for p in frontier:
            for g in gens:
                q = compose(p, g)
                if q not in index:
                    index[q] = len(elems)
                    elems.append(q)
                    nxt.append(q)
        frontier = nxt
    mul = [[index[compose(a, b)] for b in elems] for a in elems]
    return elems, index, mul


def subgroups_of_sylow(elems, mul):
    """Every subgroup of S as a bitmask over the indices of `elems`."""

    def generate(gens: list[int]) -> int:
        mask = 1
        frontier = [0]
        while frontier:
            nxt = []
            for x in frontier:
                row = mul[x]
                for g in gens:
                    y = row[g]
                    if not (mask >> y) & 1:
                        mask |= 1 << y
                        nxt.append(y)
            frontier = nxt
        return mask

    def maximal_subgroups(M: int):
        els = bits(M)
        phi = generate(sorted({mul[x][x] for x in els}))
        phi_els = bits(phi)
        coset: dict[int, int] = {}
        reps: list[int] = []
        for x in els:
            if x in coset:
                continue
            cid = len(reps)
            reps.append(x)
            for f in phi_els:
                coset[mul[x][f]] = cid
        r = len(reps).bit_length() - 1
        assert 1 << r == len(reps), "M/Phi(M) is not a 2-group"
        coord = {coset[0]: 0}
        nb = 0
        for x in reps:
            if coset[x] in coord:
                continue
            for cid, v in list(coord.items()):
                coord[coset[mul[reps[cid]][x]]] = v | (1 << nb)
            nb += 1
        assert nb == r and len(coord) == len(reps), "M/Phi(M) not elementary abelian"
        out = []
        for lam in range(1, 1 << r):
            K = 0
            for x in els:
                if bin(coord[coset[x]] & lam).count("1") % 2 == 0:
                    K |= 1 << x
            out.append(K)
        return phi, r, out

    full = (1 << len(elems)) - 1
    info = {}
    queue = [full]
    seen = {full}
    while queue:
        M = queue.pop()
        phi, r, maxs = maximal_subgroups(M)
        info[M] = (M.bit_count(), r, phi.bit_count())
        for K in maxs:
            if K not in seen:
                seen.add(K)
                queue.append(K)
    return info


def left_transversal(sylow_elems):
    covered = set()
    reps = []
    for g in itertools.permutations(range(DEG)):
        if g in covered:
            continue
        reps.append(g)
        for s in sylow_elems:
            covered.add(compose(g, s))
    return reps


# ------------------------------------------------------- group computations


_sq_cache: dict[int, int] = {}


def square_code(c: int) -> int:
    v = _sq_cache.get(c)
    if v is None:
        p = decode(c)
        v = encode(compose(p, p))
        _sq_cache[c] = v
    return v


def mul_code(a: int, b: int) -> int:
    return encode(compose(decode(a), decode(b)))


def closure_codes(gens: set[int]) -> set[int]:
    group = {ID_CODE}
    frontier = [ID_CODE]
    gl = sorted(gens)
    while frontier:
        nxt = []
        for x in frontier:
            for g in gl:
                y = mul_code(x, g)
                if y not in group:
                    group.add(y)
                    nxt.append(y)
        frontier = nxt
    return group


def orbits(group: tuple[int, ...]) -> list[frozenset]:
    seen = set()
    out = []
    for i in range(DEG):
        if i in seen:
            continue
        orb = frozenset((c >> (3 * i)) & 7 for c in group)
        seen |= orb
        out.append(orb)
    return out


def orbit_mask(orb: frozenset) -> int:
    m = 0
    for i in orb:
        m |= 7 << (3 * i)
    return m


def frattini_closed(group: tuple[int, ...], orbs: list[frozenset]) -> bool:
    """H >= Phi(H|O) for every orbit O.  Phi(H|O) is generated by the squares
    of H|O, and (h|O)^2 = (h^2)|O because O is h-invariant, so it suffices to
    test that every restricted square lies in H."""
    hset = set(group)
    full = (1 << (3 * DEG)) - 1
    for orb in orbs:
        if len(orb) == 1:
            continue
        m = orbit_mask(orb)
        keep_id = ID_CODE & (full ^ m)
        for c in group:
            if (square_code(c) & m) | keep_id not in hset:
                return False
    return True


def conj_key(group, t, tinv) -> tuple[int, ...]:
    return tuple(sorted(encode(compose(compose(t, decode(c)), tinv)) for c in group))


def conjugacy_classes(keys, b: int) -> dict[tuple, list]:
    """S_b-conjugacy classes of a conjugation-closed set of subgroups, by union-find.

    S_b is generated by (0 1) and (0 1 ... b-1), so closing under those two
    conjugations closes under all of S_b.
    """
    parent = {k: k for k in keys}

    def find(k):
        while parent[k] != k:
            parent[k] = parent[parent[k]]
            k = parent[k]
        return k

    gens = []
    if b >= 2:
        gens.append(from_cycles([(0, 1)]))
    if b >= 3:
        gens.append(from_cycles([tuple(range(b))]))
    for k in keys:
        for g in gens:
            k2 = conj_key(k, g, inverse(g))
            assert k2 in parent, "a conjugate left the set"
            a, c = find(k), find(k2)
            if a != c:
                parent[a] = c
    classes: dict[tuple, list] = {}
    for k in keys:
        classes.setdefault(find(k), []).append(k)
    return classes


def invariants(group: tuple[int, ...]) -> dict:
    els = [decode(c) for c in group]
    centre = sum(1 for a in els if all(compose(a, b) == compose(b, a) for b in els))
    order_of = Counter()
    for a in els:
        k, x = 1, a
        while x != ID:
            x = compose(x, a)
            k += 1
        order_of[k] += 1
    return {
        "centre": centre,
        "involutions": order_of[2],
        "exponent": max(order_of),
        "element_orders": {str(k): v for k, v in sorted(order_of.items())},
    }


# ------------------------------------------------------------------- driver


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__.split("\n\n")[0])
    ap.add_argument("--lattice-dir", type=pathlib.Path, default=ROOT / "data")
    ap.add_argument("--out", type=pathlib.Path, default=ROOT / "data" / "census8.json")
    args = ap.parse_args()

    failures: list[str] = []

    def check(ok: bool, label: str) -> None:
        print(f"  [{'pass' if ok else 'FAIL'}] {label}")
        if not ok:
            failures.append(label)

    t0 = time.time()
    elems, _, mul = build_sylow()
    print(f"Sylow 2-subgroup of S_8: order {len(elems)}")
    check(len(elems) == 128, "Sylow 2-subgroup of S_8 has order 2^7")

    info = subgroups_of_sylow(elems, mul)
    print(f"subgroups of the Sylow 2-subgroup: {len(info)}  ({time.time() - t0:.1f}s)")

    reps = left_transversal(elems)
    check(len(reps) == 315, "left transversal of S in S_8 has 8!/128 = 315 elements")

    all_subs: dict[tuple[int, ...], tuple[int, int]] = {}
    for t in reps:
        tinv = inverse(t)
        conj = [encode(compose(compose(t, p), tinv)) for p in elems]
        for M, (_, r, phi) in info.items():
            key = tuple(sorted(conj[i] for i in bits(M)))
            if key not in all_subs:
                all_subs[key] = (r, phi)
    print(f"2-subgroups of S_8: {len(all_subs)}  ({time.time() - t0:.1f}s)")

    # ---- per-subgroup analysis
    rows = []
    for key, (r, phi) in all_subs.items():
        orbs = orbits(key)
        moved = [i for o in orbs if len(o) > 1 for i in o]
        top = max(moved) + 1 if moved else 0
        rows.append(
            {
                "key": key,
                "order": len(key),
                "d": r,
                "phi": phi,
                "orbits": orbs,
                "top": top,
                "fc": frattini_closed(key, orbs),
                "exp2": all(square_code(c) == ID_CODE for c in key),
            }
        )
    print(f"per-subgroup analysis done ({time.time() - t0:.1f}s)")

    # ---- cross-check against the independent lattice enumeration
    print("\n== 2-subgroup totals vs data/lattice_n{n}.json (src/subgroups.c) ==")
    two_sub_hist = {}
    for n in range(1, DEG + 1):
        hist = Counter(row["order"] for row in rows if row["top"] <= n)
        two_sub_hist[n] = dict(sorted(hist.items()))
        lat = json.loads((args.lattice_dir / f"lattice_n{n}.json").read_text())
        lat_hist = {int(k): v for k, v in lat["order_histogram"].items()}
        want = {o: c for o, c in lat_hist.items() if o & (o - 1) == 0}
        check(
            dict(hist) == want,
            f"n={n}: 2-subgroups by order {dict(sorted(hist.items()))} match the lattice",
        )

    print("\n== conjugacy classes of 2-subgroups vs class_order_histogram in the lattice ==")
    for n in range(1, DEG + 1):
        keys_n = [row["key"] for row in rows if row["top"] <= n]
        cls_n = conjugacy_classes(keys_n, n)
        hist = Counter(len(root) for root in cls_n)
        lat = json.loads((args.lattice_dir / f"lattice_n{n}.json").read_text())
        want = {int(k): v for k, v in lat["class_order_histogram"].items() if int(k) & (int(k) - 1) == 0}
        check(dict(hist) == want, f"n={n}: {len(cls_n)} S_{n}-classes of 2-subgroups, by order {dict(sorted(hist.items()))}, match the lattice")
    print(f"  ({time.time() - t0:.1f}s)")

    print("\n== elementary abelian totals ==")
    sys.path.insert(0, str(ROOT / "src"))
    import elemab  # noqa: E402

    for n in range(1, DEG + 1):
        ranks = Counter(row["order"].bit_length() - 1 for row in rows if row["top"] <= n and row["exp2"])
        got = [ranks[k] for k in range(max(ranks) + 1)]
        want = elemab.rank_counts(n)
        check(got == want, f"n={n}: elementary abelian ranks {got} match elemab.rank_counts")
    got8 = [
        Counter(row["order"].bit_length() - 1 for row in rows if row["exp2"])[k] for k in range(5)
    ]
    check(got8 == EXPECTED_RANKS_N8, "n=8 ranks equal NOTES.md [1, 763, 6685, 4440, 350]")

    # ---- census of transitive 2-subgroups of S_b
    print("\n== transitive 2-subgroups of S_b ==")
    census = {}
    for b in (1, 2, 4, 8):
        block = frozenset(range(b))
        if b == 1:
            trans = [row for row in rows if row["order"] == 1]
        else:
            trans = [row for row in rows if row["top"] <= b and block in row["orbits"]]
        keys = {row["key"]: row for row in trans}
        classes = conjugacy_classes(keys, b)
        cls_out = []
        for root, members in classes.items():
            row = keys[root]
            inv = invariants(root)
            phi_group = closure_codes({square_code(c) for c in root})
            assert len(phi_group) == row["phi"], "Phi mismatch between descent and closure"
            cls_out.append(
                {
                    "order": row["order"],
                    "d": row["d"],
                    "log2_phi": row["phi"].bit_length() - 1,
                    "class_size": len(members),
                    **inv,
                }
            )
        cls_out.sort(key=lambda c: (c["order"], c["d"], c["log2_phi"], c["centre"], c["involutions"]))
        by_type = Counter()
        for c in cls_out:
            by_type[(c["d"], c["log2_phi"])] += c["class_size"]
        census[b] = {
            "transitive_total": len(keys),
            "classes": cls_out,
            "count_by_d_log2phi": {f"{d},{p}": v for (d, p), v in sorted(by_type.items())},
        }
        print(f"  b={b}: {len(keys)} transitive 2-subgroups in {len(cls_out)} classes")
        for c in cls_out:
            print(
                f"     order {c['order']:3d}  d={c['d']}  |Phi|=2^{c['log2_phi']}  "
                f"|Z|={c['centre']:2d}  involutions={c['involutions']:3d}  "
                f"exponent={c['exponent']}  class size {c['class_size']}"
            )

    # b = 4 is small enough to know by hand: V4 (1, d=2), C4 (3, d=1), D8 (3, d=2).
    check(
        census[4]["count_by_d_log2phi"] == {"1,1": 3, "2,0": 1, "2,1": 3},
        "b=4: regular V4 x1 (d=2), C4 x3 (d=1), D8 x3 (d=2)",
    )
    check(census[2]["count_by_d_log2phi"] == {"1,0": 1}, "b=2: C2 x1 (d=1)")
    # McIver-Neumann: d(G) <= n/2 for G <= S_n, n >= 4 (also for n = 2, 8 here)
    check(
        all(c["d"] <= b // 2 for b in (2, 4, 8) for c in census[b]["classes"]),
        "every transitive 2-subgroup of S_b has d <= b/2 (McIver-Neumann)",
    )
    # The GAP/Magma TransitiveGroups library, as tabulated at
    # https://people.maths.bris.ac.uk/~matyd/GroupNames/T15.html (read September 22, 2026):
    # the degree-8 2-groups are 8T1-5, 8T6-11, 8T15-22, 8T26-31, 8T35, and 8T22 is 2^(1+4)_+.
    by_order8 = Counter(c["order"] for c in census[8]["classes"])
    check(
        dict(sorted(by_order8.items())) == {8: 5, 16: 6, 32: 8, 64: 6, 128: 1},
        "b=8: classes by order 8:5 16:6 32:8 64:6 128:1, as in the TransitiveGroups library",
    )
    dense8 = [c for c in census[8]["classes"] if c["d"] == 4]
    check(
        len(dense8) == 1 and (dense8[0]["order"], dense8[0]["centre"], dense8[0]["involutions"]) == (32, 2, 19),
        "b=8: one class has d = 4, of order 32 with |Z| = 2 and 19 involutions: 8T22 = 2^(1+4)_+",
    )

    # ---- Frattini-closed 2-subgroups, n <= 8
    print("\n== Frattini-closed 2-subgroups of S_n ==")
    fc_out = {}
    for n in range(1, DEG + 1):
        sel = [row for row in rows if row["top"] <= n and row["fc"]]
        hist = Counter(row["order"] for row in sel)
        fc_out[n] = {
            "count": len(sel),
            "order_histogram": {str(k): v for k, v in sorted(hist.items())},
            "sum_log2_order": sum(row["order"].bit_length() - 1 for row in sel),
            "two_subgroups": sum(1 for row in rows if row["top"] <= n),
            "elementary_abelian": sum(1 for row in rows if row["top"] <= n and row["exp2"]),
        }
        print(
            f"  n={n}: {len(sel):6d} of {fc_out[n]['two_subgroups']:6d} 2-subgroups "
            f"are Frattini-closed; orders {dict(sorted(hist.items()))}"
        )
    check(
        all(row["fc"] for row in rows if row["exp2"]),
        "every elementary abelian 2-subgroup is Frattini-closed (Phi = 1 on each orbit)",
    )

    out = {
        "description": "Brute-force census of 2-subgroups of S_n, n <= 8 (src/census8.py)",
        "sylow_subgroups": len(info),
        "two_subgroups_by_order": {str(n): {str(k): v for k, v in h.items()} for n, h in two_sub_hist.items()},
        "transitive": {str(b): v for b, v in census.items()},
        "frattini_closed": {str(n): v for n, v in fc_out.items()},
        "checks_failed": failures,
        "seconds": round(time.time() - t0, 1),
    }
    args.out.parent.mkdir(parents=True, exist_ok=True)
    args.out.write_text(json.dumps(out, indent=1) + "\n")
    shown = args.out.resolve().relative_to(ROOT) if args.out.resolve().is_relative_to(ROOT) else args.out
    print(f"\nwrote {shown}  ({time.time() - t0:.1f}s)")
    print(f"{len(failures)} failed" if failures else "all checks passed")
    return 1 if failures else 0


if __name__ == "__main__":
    sys.exit(main())
